#include "input_glyphs_constants.h"
void InputGlyphsConstants::_bind_methods() {
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_INVALID);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_A);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_B);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_X);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_Y);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_VIEW); // Select/Back
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_MENU); // Start
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTBUMPER);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTBUMPER);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTTRIGGER_PULL);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTTRIGGER_CLICK);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTTRIGGER_PULL);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTTRIGGER_CLICK);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_MOVE);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_CLICK);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_DPADNORTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_DPADSOUTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_DPADWEST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_LEFTSTICK_DPADEAST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_MOVE);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_CLICK);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_DPADNORTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_DPADSOUTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_DPADWEST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_RIGHTSTICK_DPADEAST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_DPAD_NORTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_DPAD_SOUTH);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_DPAD_WEST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_DPAD_EAST);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_DPAD_MOVE);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_MISC1); // Xbox Series X share button, PS5 microphone button, Nintendo Switch Pro capture button, Amazon Luna microphone button
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_PADDLE1); // Xbox Elite paddle P1 (upper left, facing the back)
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_PADDLE2); // Xbox Elite paddle P3 (upper right, facing the back)
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_PADDLE3); // Xbox Elite paddle P2 (lower left, facing the back)
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_PADDLE4); // Xbox Elite paddle P4 (lower right, facing the back)
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_TRACKPAD_CLICK);
	BIND_ENUM_CONSTANT(INPUT_ORIGIN_COUNT);

	BIND_ENUM_CONSTANT(UNKNOWN);
	BIND_ENUM_CONSTANT(STEAM_CONTROLLER);
	BIND_ENUM_CONSTANT(XBOX_360_CONTROLLER);
	BIND_ENUM_CONSTANT(XBOX_ONE_CONTROLLER);
	BIND_ENUM_CONSTANT(GENERIC_XINPUT_CONTROLLER);
	BIND_ENUM_CONSTANT(PS3_CONTROLLER);
	BIND_ENUM_CONSTANT(PS4_CONTROLLER);
	BIND_ENUM_CONSTANT(PS5_CONTROLLER);
	BIND_ENUM_CONSTANT(SWITCH_PRO_CONTROLLER);
	BIND_ENUM_CONSTANT(STEAM_DECK_CONTROLLER);
	BIND_ENUM_CONSTANT(INPUT_TYPE_MAX);
}
